@startuml jetons

enum CouleurJeton { 
    RUBIS
    SAPHIR
    ÉMERAUDE
    ONYX
    DIAMANT
    OR
    PERLE
}

class Jeton {
    - couleur : CouleurJeton
    + Jeton(CouleurJeton c) : Jeton
    + getCouleur() const : CouleurJeton
}

class LotDeJetons {
    - jetons : array<Jeton*, 25>

    + getNbJetons() : size_t
    + getJetons(size_t i) : Jeton&
    + LotDeJetons()
    + ~LotDeJetons()
}

class Privilege {
    + Privilege() = default
}

class LotPrivilege {
    - privileges : array<Privilege*, 3>

    + getNbPrivileges() : size_t
    + getPrivileges(size_t i) : Privilege&
    + LotPrivilege()
    + ~LotPrivilege()
}

class Sac{
    - jetons : vector<Jetons*>

    + explicit Sac(const LotJetons& lot)
    + bool estVide() 
    + getNbJetons() : size_t
    + ajoutJetons(const Jetons* j) : void
    + piocherJetons() : Jetons&
}

class Plateau {
    - jetons : array<array<const Jeton*, 5>, 5>
    - privileges : vector<const Privilege*>
    - liste_pos : array<tuple<size_t, size_t>, 25>

    + recupererJeton(size_t i, size_t j) : const Jeton&
    + recupererPrivilege() : const Privilege&
    + positionerJeton(const Jeton* jeton)
    + poserPrivilege(const Privilege* privilege)
    + Plateau(const LotPrivilege& lot)
}

Jeton "25" --* LotDeJetons
Jeton "0..25" -o "0..1" Sac

Privilege "3" --* LotPrivilege

Jeton "0..25" -o "0..1" Plateau
Privilege "0..3" -o "0..1" Plateau

@enduml